[package]
name = "jz_offer"
version = "0.1.0"
authors = ["Albert Chen <albert.chen.dao@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.2.0"
parking_lot = "0.3"
regex = "1"
